# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- script: npm install 
  displayName: 'npm install and Wauuu'
  
- script: npm run lint  
  displayName: 'npm lint  and Wauuu'
 
- script: npm run test  
  displayName: 'npm test and Wauuu'

- script: npm build  
  displayName: 'npm build and Wauuu'

